export const SITE = {
  website: "https://leolwin.com",
  author: "Leo Lwin",
  profile: "",
  desc: "Sharing some tech stuff :)",
  title: "Leo Lwin",
  ogImage: "og-leolwin.jpg",
  lightAndDarkMode: true,
  postPerIndex: 4,
  postPerPage: 4,
  scheduledPostMargin: 15 * 60 * 1000,
  showArchives: true,
  showBackButton: true,
  editPost: {
    enabled: true,
    text: "Spotted a mistake?",
    url: "https://github.com/leolwin999/leolwin-com/edit/main/",
  },
  dynamicOgImage: true,
  dir: "ltr",
  lang: "en",
  timezone: "Asia/Yangon",
} as const;
